apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: df-statefulset
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.4
          env:
            - name: POSTGRES_USER
              value: "doc"
            - name: POSTGRES_DB
              value: "database"
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5432
              name: access
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/bin/pg_isready
                - --username=doc
                - --dbname=database
            failureThreshold: 20
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: postgres-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-mount
          persistentVolumeClaim:
            claimName: db-volume
